kind: Deployment
apiVersion: apps/v1
metadata:
  name: webdemo
  namespace: default
  labels:
    app: webdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webdemo
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webdemo
    spec:
      containers:
        - name: webdemo
          image: narioinc89/node-web-app
          ports:
            - containerPort: 8081
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  
---
  
kind: Service
apiVersion: v1
metadata:
  name: webdemo
  namespace: default
  labels:
    app: webdemo
  annotations:
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8081
  selector:
    app: webdemo
  clusterIP: 10.99.210.150
  clusterIPs:
    - 10.99.210.150
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster

